services:
  web:
    image: ${CONTAINER_REGISTRY}${PROJECT_NAME}/web-otel:${IMAGE_TAG}
    container_name: ${PROJECT_NAME}-web
    hostname: smplapp-nginx
    environment:
      - NGINX_ENVSUBST_FILTER=^OTEL_.*|^FASTCGI_PARAMS_ADDFILE
      - OTEL_TRACE=on
      - OTEL_ENDPOINT=otel-collector.tracing.svc.cluster.local:4317
      - OTEL_SERVICE_NAME=${PROJECT_NAME}-web
      - OTEL_TRACE_CONTEXT=propagate
      #- FASTCGI_PARAMS_ADDFILE=empty
      - FASTCGI_PARAMS_ADDFILE=fastcgi_params-codeigniter-development
    ports:
      - "8080:8080"

    volumes:
      - fpm_shared:/var/run/php-fpm
      - ./webapp/public:/var/www/public
    depends_on:
      - app

  app:
    image: ${CONTAINER_REGISTRY}${PROJECT_NAME}/app-otel:${IMAGE_TAG}
    container_name: ${PROJECT_NAME}-app
    hostname: smplapp-app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - XDEBUG_ENABLED=1
      - XDEBUG_CLIENT_HOST=host.docker.internal  # default
      #- XDEBUG_REMOTE_HOST=host.k3d.internal # for local k3d
      - XDEBUG_CLIENT_PORT=9003
      - DEV_ENABLED=1
      - OTEL_PHP_AUTOLOAD_ENABLED=true
      - OTEL_SERVICE_NAME=${PROJECT_NAME}-app
      #- OTEL_TRACES_EXPORTER=otlp
      #- OTEL_TRACES_EXPORTER=console
      - OTEL_TRACES_EXPORTER=none
      #- OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      #TRANSPORTER PROTOCOLS: http/json, http/protobuf, grpc
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector.tracing.svc.cluster.local:4317 #grpc
      #- OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector.tracing.svc.cluster.local:4318 #http/json
      #- OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://otel-collector.tracing.svc.cluster.local:4317/v1/traces
      #- OTEL_EXPORTER_OTLP_METRICS_ENDPOINT=http://otel-collector.tracing.svc.cluster.local:4317/v1/metrics
      #- OTEL_METRICS_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=console
      - OTEL_LOGS_EXPORTER=none
      - OTEL_PROPAGATORS="baggage,tracecontext"
    volumes:
      - fpm_shared:/var/run/php-fpm
      - ./webapp:/var/www/webapp
      - ./xdebug:/tmp/xdebug

volumes:
  fpm_shared:

