services:
  nginx:
    build:
      context: .
      dockerfile: ./containers/nginx/Dockerfile
    image: ${CONTAINER_REGISTRY}${PROJECT_NAME}/${IMAGE_NAME_WEB}:${IMAGE_TAG}

  app:
    build:
      context: .
      dockerfile: ./containers/php-fpm/Dockerfile
      args:
        - BUILD_OTEL=${BUILD_OTEL}
        - BUILD_GRPC=${BUILD_GRPC}
        - BUILD_PROTOBUF=${BUILD_PROTOBUF}
    image: ${CONTAINER_REGISTRY}${PROJECT_NAME}/${IMAGE_NAME_APP}:${IMAGE_TAG}

