# this dockerignore will be used by nginx build-context
#  so, ignore all, except for webapp/public, but webapp/public/**/*.php(all .phpfile) is isnored
*
!containers
!webapp/public
webapp/public/**/*.php
