# this dockerignore will be used by nginx build-context
#  so, ignore all, except for webapp/public, but webapp/public/**/*.php(all .php file) is still ignored.
*
!containers
!webapp/public
webapp/public/**/*.php
